# Generated by Django 5.1.2 on 2024-10-22 23:19

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='flan',
            name='flan_uuid',
            field=models.UUIDField(default=uuid.uuid4()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flan',
            name='image_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flan',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flan',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
