# Generated by Django 5.1.2 on 2024-10-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_flan_descripcion_flan_flan_uuid_flan_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_form_uuid', models.UUIDField()),
                ('customer_name', models.CharField(max_length=64)),
                ('message', models.TextField(blank=True)),
                ('custumer_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
