# Generated by Django 5.1.2 on 2024-10-25 17:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rename_custumer_email_contactform_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=9999999, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactform',
            name='contact_form_uuid',
            field=models.UUIDField(default=uuid.UUID('4d334ca7-c3cc-4129-8e3b-cb5f3aab60e6')),
        ),
    ]
