# Generated by Django 5.1.2 on 2024-10-25 19:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_contactform_contact_form_uuid_cartitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flan',
            options={'permissions': [('can_view_premium', 'Can view premium flans')]},
        ),
        migrations.AddField(
            model_name='flan',
            name='is_premium',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactform',
            name='contact_form_uuid',
            field=models.UUIDField(default=uuid.UUID('8b3c16e3-a6bb-4d80-bc6a-969320dd0a49')),
        ),
    ]
